version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/vecmerge-impl"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
